CREATE TABLE app(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	app_key VARCHAR(50) NOT NULL,
	name VARCHAR(50) NOT NULL,
	user_id INTEGER NOT NULL
);

CREATE TABLE cashgame_checkpoint(
	checkpoint_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	game_id INTEGER NOT NULL,
	player_id INTEGER NOT NULL,
	type INTEGER NOT NULL,
	amount INTEGER NOT NULL,
	stack INTEGER NOT NULL,
	timestamp TIMESTAMP NOT NULL,
);

CREATE TABLE cashgame_comment(
	game_id INTEGER NOT NULL,
	comment_id INTEGER NOT NULL,
    PRIMARY KEY (game_id, comment_id)
);

CREATE TABLE comment(
	comment_id INTEGER IDENTITY(1,1) NOT NULL,
	player_id INTEGER NOT NULL,
	date TIMESTAMP NOT NULL,
	comment_text VARCHAR(1024) NOT NULL,
PRIMARY KEY 
(
	comment_id ASC
);

CREATE TABLE event(
	event_id INTEGER IDENTITY(1,1) NOT NULL,
	name VARCHAR(50) NOT NULL,
	bunch_id INTEGER NOT NULL,
PRIMARY KEY 
(
	event_id ASC
);

CREATE TABLE event_cashgame(
	event_id INTEGER NOT NULL,
	game_id INTEGER NOT NULL,
PRIMARY KEY 
(
	event_id ASC,
	game_id ASC
);

CREATE TABLE game(
	game_id INTEGER IDENTITY(1,1) NOT NULL,
	date date NOT NULL,
	timestamp TIMESTAMP NOT NULL,
	status INTEGER NOT NULL,
	homegame_id INTEGER NOT NULL,
	location_id INTEGER NOT NULL,
PRIMARY KEY 
(
	game_id ASC
);

CREATE TABLE homegame(
	homegame_id INTEGER IDENTITY(1,1) NOT NULL,
	name VARCHAR(50) NOT NULL,
	display_name VARCHAR(50) NULL,
	description VARCHAR(50) NULL,
	timezone VARCHAR(50) NOT NULL,
	default_buyin INTEGER NOT NULL,
	currency VARCHAR(3) NOT NULL,
	currency_layout VARCHAR(20) NOT NULL,
	cashgames_enabled bit NOT NULL,
	tournaments_enabled bit NOT NULL,
	videos_enabled bit NOT NULL,
	house_rules text NULL,
PRIMARY KEY 
(
	homegame_id ASC
);

CREATE TABLE location(
	id INTEGER IDENTITY(1,1) NOT NULL,
	name VARCHAR(50) NOT NULL,
	bunch_id INTEGER NOT NULL,
PRIMARY KEY 
(
	id ASC
);

CREATE TABLE player(
	player_id INTEGER IDENTITY(1,1) NOT NULL,
	homegame_id INTEGER NOT NULL,
	user_id INTEGER NULL,
	role_id INTEGER NOT NULL,
	approved bit NOT NULL,
	player_name VARCHAR(50) NULL,
	color VARCHAR(10) NULL,
PRIMARY KEY 
(
	player_id ASC
);

CREATE TABLE role(
	role_id INTEGER IDENTITY(1,1) NOT NULL,
	role_name VARCHAR(50) NOT NULL,
PRIMARY KEY 
(
	role_id ASC
);

CREATE TABLE tournament(
	tournament_id INTEGER IDENTITY(1,1) NOT NULL,
	homegame_id INTEGER NOT NULL,
	buyin INTEGER NOT NULL,
	date date NOT NULL,
	duration INTEGER NOT NULL,
	location VARCHAR(50) NOT NULL,
	timestamp TIMESTAMP NOT NULL,
	published bit NOT NULL,
PRIMARY KEY 
(
	tournament_id ASC
);

CREATE TABLE tournament_comment(
	tournament_id INTEGER NOT NULL,
	comment_id INTEGER NOT NULL,
PRIMARY KEY 
(
	tournament_id ASC
);

CREATE TABLE tournament_payout(
	tournament_id INTEGER NOT NULL,
	position INTEGER NOT NULL,
	payout INTEGER NOT NULL,
PRIMARY KEY 
(
	tournament_id ASC
);

CREATE TABLE tournament_result(
	tournament_id INTEGER NOT NULL,
	player_id INTEGER NOT NULL,
	position INTEGER NOT NULL,
PRIMARY KEY 
(
	tournament_id ASC,
	player_id ASC
);

CREATE TABLE user(
	user_id INTEGER IDENTITY(1,1) NOT NULL,
	token VARCHAR(50) NULL,
	user_name VARCHAR(50) NOT NULL,
	password VARCHAR(50) NULL,
	salt VARCHAR(50) NULL,
	role_id INTEGER NOT NULL,
	real_name VARCHAR(50) NULL,
	display_name VARCHAR(50) NOT NULL,
	email VARCHAR(50) NULL,
PRIMARY KEY 
(
	user_id ASC
);

CREATE TABLE user_sharing(
	user_id INTEGER NOT NULL,
	service_name VARCHAR(50) NOT NULL,
PRIMARY KEY 
(
	user_id ASC,
	service_name ASC
);

CREATE TABLE user_twitter(
	user_id INTEGER NOT NULL,
	twitter_name VARCHAR(100) NOT NULL,
	key VARCHAR(100) NOT NULL,
	secret VARCHAR(100) NOT NULL,
PRIMARY KEY 
(
	userId ASC
);

CREATE TABLE video(
	video_id INTEGER IDENTITY(1,1) NOT NULL,
	homegame_id INTEGER NOT NULL,
	date date NOT NULL,
	thumbnail VARCHAR(255) NOT NULL,
	length INTEGER NOT NULL,
	width INTEGER NOT NULL,
	height INTEGER NOT NULL,
	source VARCHAR(20) NOT NULL,
	type VARCHAR(20) NOT NULL,
	hidden bit NOT NULL,
PRIMARY KEY 
(
	video_id ASC
);

ALTER TABLE cashgame_checkpoint ADD DEFAULT ((0)) FOR type;

ALTER TABLE cashgame_checkpoint ADD DEFAULT ((0)) FOR amount;

ALTER TABLE cashgame_checkpoint ADD DEFAULT ((0)) FOR stack;

ALTER TABLE event ADD DEFAULT ((0)) FOR bunch_id;

ALTER TABLE game ADD CONSTRAINT df_game_timestamp DEFAULT (getdate()) FOR timestamp;

ALTER TABLE game ADD DEFAULT ((0)) FOR homegame_id;

ALTER TABLE game ADD DEFAULT ((0)) FOR location_id;

ALTER TABLE location ADD DEFAULT ((0)) FOR bunch_id;

ALTER TABLE player ADD DEFAULT ((0)) FOR approved;

ALTER TABLE cashgame_checkpoint WITH CHECK ADD CONSTRAINT fk_cashgame_checkpoint_game FOREIGN KEY(game_id)
REFERENCES game (game_id);

ALTER TABLE cashgame_checkpoint CHECK CONSTRAINT fk_cashgame_checkpoint_game;

ALTER TABLE cashgame_checkpoint WITH CHECK ADD CONSTRAINT fk_cashgame_checkpoint_player FOREIGN KEY(player_id)
REFERENCES player (player_id);

ALTER TABLE cashgame_checkpoint CHECK CONSTRAINT fk_cashgame_checkpoint_player;
