INSERT INTO [dbo].[Event] (Name) VALUES ('Pokerhelg 1')
INSERT INTO [dbo].[Event] (Name) VALUES ('Pokerhelg 2')
INSERT INTO [dbo].[Event] (Name) VALUES ('Pokerhelg 3')
INSERT INTO [dbo].[Event] (Name) VALUES ('Pokerhelg 4')
INSERT INTO [dbo].[Event] (Name) VALUES ('Pokerhelg 5')
INSERT INTO [dbo].[Event] (Name) VALUES ('Pokerhelg 6')

INSERT INTO [dbo].[EventCashgame] (EventId, GameId) VALUES (1, 8)
INSERT INTO [dbo].[EventCashgame] (EventId, GameId) VALUES (2, 228)
INSERT INTO [dbo].[EventCashgame] (EventId, GameId) VALUES (2, 229)
INSERT INTO [dbo].[EventCashgame] (EventId, GameId) VALUES (2, 230)
INSERT INTO [dbo].[EventCashgame] (EventId, GameId) VALUES (3, 261)
INSERT INTO [dbo].[EventCashgame] (EventId, GameId) VALUES (3, 262)
INSERT INTO [dbo].[EventCashgame] (EventId, GameId) VALUES (3, 263)
INSERT INTO [dbo].[EventCashgame] (EventId, GameId) VALUES (4, 2285)
INSERT INTO [dbo].[EventCashgame] (EventId, GameId) VALUES (4, 2286)
INSERT INTO [dbo].[EventCashgame] (EventId, GameId) VALUES (4, 2287)
INSERT INTO [dbo].[EventCashgame] (EventId, GameId) VALUES (5, 6297)
INSERT INTO [dbo].[EventCashgame] (EventId, GameId) VALUES (5, 6298)
INSERT INTO [dbo].[EventCashgame] (EventId, GameId) VALUES (5, 6299)
INSERT INTO [dbo].[EventCashgame] (EventId, GameId) VALUES (6, 7311)
INSERT INTO [dbo].[EventCashgame] (EventId, GameId) VALUES (6, 7312)
INSERT INTO [dbo].[EventCashgame] (EventId, GameId) VALUES (6, 7313)