name: Deploy to heroku.

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Install Heroku Cli
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          usedocker: true
